Retry honeycomb marker creation (#958)
### TL;DR

Added retry logic for Honeycomb marker creation during deployments to handle transient failures.

Example run: https://github.com/cyberworlds/cyberworlds/actions/runs/20762320376/job/59620187553

```
Total Upload: 1318.88 KiB / gzip: 281.07 KiB
Worker Startup Time: 20 ms
Your worker has access to the following bindings:
- R2 Buckets:
  - AvatarsBucket: cyberworlds-avatars
  - AppStaticBucket: cyberworlds-app-static
  - FilesBucket: cyberworlds-files
- Vars:
  - CORS_TRUSTED_ORIGINS: [
 "https://alpine.inc"
]
Uploaded resource-service (7.42 sec)
Deployed resource-service triggers (3.36 sec)
  resources.alpine.inc (custom domain)
Current Version ID: df3ecd8a-11a9-4d1f-ab62-8feac670bcc4
Shutdown started by exception:
UnknownError: Couldn’t create Honeycomb marker: something went wrong! (status code: 500)
    at HoneycombTracerClient.createMarker (file:///home/runner/_work/cyberworlds/cyberworlds/bazel-bin/server/deploy/script/script.sh.runfiles/cyberworlds/server/tracer/honeycomb_tracer_client.js:142:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async actuallyDeploy (file:///home/runner/_work/cyberworlds/cyberworlds/bazel-bin/server/deploy/script/script.sh.runfiles/cyberworlds/server/deploy/script/internal/deploy.js:143:5)
    at async Context.with (file:///home/runner/_work/cyberworlds/cyberworlds/bazel-bin/server/deploy/script/script.sh.runfiles/cyberworlds/shared/context/context.js:186:27)
    at async TracerSpan.withSpan (file:///home/runner/_work/cyberworlds/cyberworlds/bazel-bin/server/deploy/script/script.sh.runfiles/cyberworlds/shared/tracer/tracer_base.js:22:27)
    at async deploy (file:///home/runner/_work/cyberworlds/cyberworlds/bazel-bin/server/deploy/script/script.sh.runfiles/cyberworlds/server/deploy/script/internal/deploy.js:78:9)
    at async Module.run (file:///home/runner/_work/cyberworlds/cyberworlds/bazel-bin/server/deploy/script/script.sh.runfiles/cyberworlds/server/deploy/script/deploy_service.js:56:5)
    at async main (file:///home/runner/_work/cyberworlds/cyberworlds/bazel-bin/server/deploy/script/script.sh.runfiles/cyberworlds/server/node/run_service.js:197:13) {
  code: 2,
  [cause]: undefined
}
Shutdown started (pid: 37052)
Shutdown finished (pid: 37052)
```